# Generated by Django 4.2.2 on 2023-06-29 05:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_empresa_usuarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="pais",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
