# Generated by Django 4.2.2 on 2023-06-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_empresa_pais"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="google_ads",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="meta_ads",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
