# Generated by Django 4.2.2 on 2023-06-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_empresa_google_ads_alter_empresa_meta_ads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="google_ads",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="meta_ads",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
