# Generated by Django 4.2.2 on 2023-06-29 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0006_alter_empresa_google_ads_alter_empresa_meta_ads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="usuarios",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
